### ISSUE TITLE
remove link plugin gives ugly warnings

### ISSUE THREAD

**Issue by froomkin** [fluffy-critter/Feed-on-Feeds#6] opened 2015-09-12 18:14 UTC
Just installed the latest version.  Just got error messages like these above my feeds when I updated and viewed:

Warning: DOMDocument::loadHTML(): Empty string supplied as input in [...]/FeedOnFeeds/plugins/remove_link_tags.php on line 10

Warning: DOMDocument::loadHTML(): Empty string supplied as input in [...]/FeedOnFeeds/plugins/remove_link_tags.php on line 10

Note that [...] is the correct absolute path to my FoF installation.

Don't know if it's relevant but I've set FoF to show me up to 25 entries per page, and there were only 19 entries from the feeds I am following (which is likely correct since I was up to date).

**Comment by fluffy-critter** [comment] 2015-09-12 19:14
Is any other content appearing? What if you disable that plugin? Also what version of php are you running?

##

**Comment by froomkin** [comment] 2015-09-12 20:02
PHP 5.6 fastCGI
ANd yes, I see all 19 entries just fine below the error messages, which 
are at the top, right below the line "feed on feeds - showing 19 items 
tagged unread"

If I untick the plugin, the error messages are gone; but due to the 
passage of time I'm up to 45 entries.  And when I click the plugin back 
on, the error messages are gone.

So  I mark 25 items as read (plugin on), leaving 20 - error message comes 
back.

Disable plugin.  No error messages.

Enable plugin....and error is back again:

feed on feeds - showing 20 items tagged unread

Warning: DOMDocument::loadHTML(): Empty string supplied as input in 
[...]/FeedOnFeeds/plugins/remove_link_tags.php on 
line 10

Warning: DOMDocument::loadHTML(): Empty string supplied as input in 
[...]/FeedOnFeeds/plugins/remove_link_tags.php on 
line 10

Conclusion: error is reproducable if number of posts available < max 
number of posts per screen AND plugin is on.

On Sat, 12 Sep 2015, plaidfluff wrote:

> Is any other content appearing? What if you disable that plugin? Also what
> version of php are you running?
> 
> ## 
> 
> Sent from my tin cans and a piece of string.
> 
> > On Sep 12, 2015, at 11:14 AM, froomkin notifications@github.com wrote:
> > 
> > Just installed the latest version. Just got error messages like these
> > above my feeds when I updated and viewed:
> > 
> > Warning: DOMDocument::loadHTML(): Empty string supplied as input in
> > [...]/FeedOnFeeds/plugins/remove_link_tags.php on line 10
> > 
> > Warning: DOMDocument::loadHTML(): Empty string supplied as input in
> > [...]/FeedOnFeeds/plugins/remove_link_tags.php on line 10
> > 
> > Note that [...] is the correct absolute path to my FoF installation.
> > 
> > Don't know if it's relevant but I've set FoF to show me up to 25 entries
> > per page, and there were only 19 entries from the feeds I am following
> > (which is likely correct since I was up to date).
> > 
> > ―
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on
> GitHub.[AFfE1DuOsz3O0Fdc3YU0m-x3s6K_mLbkks5oxHELgaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 | +1 (305) 284-4285 |  froomkin@law.tm
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                         -->It's HOT here.<--

**Comment by fluffy-critter** [comment] 2015-09-12 20:11
Hm, that's really strange. There shouldn't be anything causing a plugin to care about how many messages are visible - they are run at the time that an item is formatted for display, completely independently of one another.  Is it possible that it's just a coincidence and you have a feed that provides RSS items without a `<description>` body? I can see that possibly causing a problem.

Could you provide the permalinks of some items where this is happening, ideally from more than one feed source? That would help to narrow it down.

**Comment by fluffy-critter** [comment] 2015-09-12 20:13
(Also by "any other content" I meant content within the items where the messages are occurring, and not content from other items. Sorry for being unclear.)

**Comment by froomkin** [comment] 2015-09-12 20:48
It's happening ONLY at the top of the output - before any feeds.  And doesn't repeat.  So it doesn't seem to be connected with any particular feed or post.

![fof-bug2](https://cloud.githubusercontent.com/assets/5752020/9833672/0a3a7466-596e-11e5-983c-5d247d99a6f7.png)

And that's it, doesn't repeat.   And it did the same thing when a different post was at the top.  Clicking 'mark read' for top post doesn't make it go away.  Neither does clicking "Unread (19)" to make the page refresh.

**Comment by fluffy-critter** [comment] 2015-09-12 20:53
That screenshot doesn't show me what I need. Could you include the entire window, please, with as many items visible as possible?

Thanks.

**Comment by fluffy-critter** [comment] 2015-09-12 20:55
Also those errors ARE connected with a particular feed or post, but they're not being formatted as part of it because of the way that PHP error messages work. (Which is why I need to see the full window and as many items as possible.)

I'm willing to bet that the problem is with two of the visible items.

**Comment by froomkin** [comment] 2015-09-12 20:59
I suppose if you send me a non-public address where my reading habits 
won't be memorialized for the world I can send you more.  But one screen 
wont do much for you.

All you will see is a very long list of blogs on the left, and the first 
of 19 posts, some quite long, on the right.  It looks like it always did. 
Or can you tell me more specifically what you want?  There are no other 
error messages besides those at the top.  It's 21 screens to get to the 
bottom of it all.

On Sat, 12 Sep 2015, plaidfluff wrote:

> That screenshot doesn't show me what I need. Could you include the entire window, please, with as many items visible as
> possible?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub.[AFfE1MOUS72A68eBL3Y7JC74ZGsRkaP4ks5oxIhJgaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 | +1 (305) 284-4285 |  froomkin@law.tm
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                         -->It's HOT here.<--

**Comment by fluffy-critter** [comment] 2015-09-12 21:03
I’d be looking for any entries where the body of the entry itself is empty.

Also, if you enable logging, that MIGHT put some clues into the log as to which entries are generating the errors, although the log is a giant mess.

**Comment by froomkin** [comment] 2015-09-12 21:04
There are only 3 feeds with exactly two posts currently, and one with 3 
and one with 4.  I could try marking as read one post from each at a time 
to see if one of the error messages goes away.  If it does, we know it's 
connected to that feed.

Right now my bet would be http://feeds.feedburner.com/LPBNRightCoast which 
comes from http://rightcoast.typepad.com/rightcoast/ and is currently 
showing me only a headline, no text at all, even though there is text in 
the feed source.

On Sat, 12 Sep 2015, plaidfluff wrote:

> Also those errors ARE connected with a particular feed or post, but they're not being formatted as part of it because of
> the way that PHP error messages work. (Which is why I need to see the full window and as many items as possible.)
> 
> I'm willing to bet that the problem is with two of the visible items.
> 
> —
> Reply to this email directly or view it on GitHub.[AFfE1JfEg5Pr_D3NtSh_FQ8LVSmsjhaIks5oxIingaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 | +1 (305) 284-4285 |  froomkin@law.tm
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                         -->It's HOT here.<--

**Comment by fluffy-critter** [comment] 2015-09-12 21:06
Hm, that's probably it - it looks like it's using `<content:encoded>` instead of `<description>`. I haven't seen that come up in RSS before...

**Comment by froomkin** [comment] 2015-09-12 21:07
Bingo.  Two empties from The Right Coast.  Blog is 
http://rightcoast.typepad.com/rightcoast/  and feed is 
http://feeds.feedburner.com/LPBNRightCoast

On Sat, 12 Sep 2015, plaidfluff wrote:

> I’d be looking for any entries where the body of the entry itself is empty.
> 
> Also, if you enable logging, that MIGHT put some clues into the log as to which entries are generating the errors,
> although the log is a giant mess.
> 
> —
> Reply to this email directly or view it on GitHub.[AFfE1KWGvdEeAGIEpYyB2L9Xrfcgqcynks5oxIq6gaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 | +1 (305) 284-4285 |  froomkin@law.tm
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                         -->It's HOT here.<--

**Comment by fluffy-critter** [comment] 2015-09-12 21:07
SimplePie has supported `content:encoded` since [version 0.93](http://simplepie.org/wiki/misc/release_notes/simplepie_0.93). I bet FoF just needs to fall back to that if it's available.

**Comment by fluffy-critter** [comment] 2015-09-12 21:16
Okay, I'm reproducing it with that feed. I'll try to figure out why it's getting an empty `<content>` chunk. This one seems kind of weird and might take me a while to track down.

**Comment by fluffy-critter** [comment] 2015-09-12 21:22
Okay, if you pull the `fluffy/fix-content-encoded` branch (`git pull origin fluffy/fix-content-encoded` or whatever) you'll get a temporary fix that suppresses the warnings, although that still doesn't address the root cause, which I'm still investigating.

**Comment by fluffy-critter** [comment] 2015-09-12 21:23
Er, rather, what you'll probably want to do is:

```
git pull
git checkout fluffy/fix-content-encoded
```

which should put you on that (temporary) branch.

**Comment by froomkin** [comment] 2015-09-12 22:09
How do I get off it later?

On Sat, 12 Sep 2015, plaidfluff wrote:

> Er, rather, what you'll probably want to do is:
> 
> git pull
> git checkout fluffy/fix-content-encoded
> 
> which should put you on that (temporary) branch.
> 
> —
> Reply to this email directly or view it on GitHub.[AFfE1IfVG68wymDW_695ZZPokFYk2kEyks5oxI9IgaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 | +1 (305) 284-4285 |  froomkin@law.tm
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                         -->It's HOT here.<--

**Comment by fluffy-critter** [comment] 2015-09-12 22:13
`git checkout master` will switch you back to the release branch. Easy peasy.

**Comment by fluffy-critter** [comment] 2016-03-18 06:27
Oh hey, looks like the upstream problem has been fixed. I'll see about upgrading FoF to the latest SimplePie.

**Comment by fluffy-critter** [comment] 2016-03-18 08:10
Okay, I've upgraded to 1.4-dev and rejiggered some other stuff. Please do the following:

```
git checkout master
git pull
```

and see if that fixes things. You may need to delete and re-add the affected feed (and possibly delete the files in your `cache/` directory) to see things working right.

**Comment by froomkin** [comment] 2016-03-18 13:05
Great! Please let me know when that happens and I'll exhume the 
instructions for upgrading.

On Thu, 17 Mar 2016, plaidfluff wrote:

> Oh hey, looks like the upstream problem has been fixed. I'll see about upgrading FoF to the latest SimplePie.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[AFfE1JA-3B9hISaKuKsZey6BUqNcdTghks5pukXIgaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 |+1 (305) 284-4285|ssrn:bit.ly/1XlTJLz
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                     -->It's cool here.<--

**Comment by froomkin** [comment] 2016-03-18 13:13
Um?

[ds8098]$ git checkout master
Already on 'master'
Your branch is ahead of 'fof/master' by 26 commits.
[ds8098]$ git pull
From http://git.beesbuzz.biz/FeedOnFeeds
    358aa2b..5272e10  master     -> fof/master
Already up-to-date.

On Fri, 18 Mar 2016, plaidfluff wrote:

> Okay, I've upgraded to 1.4-dev and rejiggered some other stuff. Please do the following:
> 
> git checkout master
> git pull
> 
> and see if that fixes things. You may need to delete and re-add the affected feed (and possibly delete the files in your
> cache/ directory) to see things working right.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[AFfE1AlPp-LSL-r9c1_weT_RjQ_kNi9nks5pul3_gaJpZM4F8THm.gif]

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 |+1 (305) 284-4285|ssrn:bit.ly/1XlTJLz
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                     -->It's cool here.<--

**Comment by fluffy-critter** [comment] 2016-03-18 15:55
Oh, you're tracking my private git repo as origin. Sorry about that. I just synced them up - it should work now.

**Comment by froomkin** [comment] 2016-03-18 16:41
now if we just fix the rendering of 
http://feeds.feedburner.com/sluggy_freelance ....

(Actually, I have another wishlist item: an option to move the links to 
"old to new" and "Mark all read" etc. to the bottom of the page instead of 
the top.)

## 

A. Michael Froomkin, http://law.tm
Laurie Silvers & Mitchell Rubenstein Distinguished Professor of Law
Editor, Jotwell: The Journal of Things We Like (Lots),  jotwell.com
Program Chair, We Robot 2016 |+1 (305) 284-4285|ssrn:bit.ly/1XlTJLz
U. Miami School of Law, P.O. Box 248087, Coral Gables, FL 33124 USA
                     -->It's cool here.<--

**Comment by fluffy-critter** [comment] 2016-03-18 17:35
I'll look at sluggy when I get a chance. IIRC that feed is screwy because it relies on custom linked CSS, which is really difficult to support right. 

You can override/customize layout elements by providing a user style sheet. That's probably going to be the easiest way to move the links to the bottom. 

##

**Comment by fluffy-critter** [comment] 2016-07-02 01:32
Closing this issue since the original has been addressed. If you still want to see fixes for the other things you mentioned please open other issues. Thanks!

**Closed as completed** 2016-07-02 01:31 UTC
